---
# Ansible inventory in YAML format

all:
  children:
    jenkins:
      hosts:
        jenkins-server:
          ansible_host: "<Jenkins-EC2-IP>"
    
    sonarqube:
      hosts:
        sonarqube-server:
          ansible_host: "<SonarQube-EC2-IP>"
    
    nexus:
      hosts:
        nexus-server:
          ansible_host: "<Nexus-EC2-IP>"
    
    monitoring:
      hosts:
        prometheus:
          ansible_host: "<Prometheus-EC2-IP>"
        grafana:
          ansible_host: "<Grafana-EC2-IP>"
    
    dev:
      hosts:
        dev-server:
          ansible_host: "<Dev-Environment-EC2-IP>"
    
    build:
      hosts:
        build-server:
          ansible_host: "<Build-Environment-EC2-IP>"
    
    deploy:
      hosts:
        deploy-server:
          ansible_host: "<Deployment-Environment-EC2-IP>"
    
    cicd:
      children:
        jenkins: {}
        sonarqube: {}
        nexus: {}
    
    environments:
      children:
        dev: {}
        build: {}
        deploy: {}
  
  vars:
    ansible_user: "ec2-user"
    ansible_ssh_private_key_file: "~/.ssh/DevOpsKey.pem"
    ansible_python_interpreter: "/usr/bin/python3"