name: CI/CD Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  notify-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Jenkins
        run: |
          curl -X POST http://<Jenkins-EC2-IP>:8080/generic-webhook-trigger/invoke \
          -H "Content-Type: application/json" \
          -d '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
